// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSKn6eYn7aJDjuo-b79yqwZr5rtlz1zoE',
    appId: '1:735015269216:web:25661c159461666ea6a405',
    messagingSenderId: '735015269216',
    projectId: 'cheezy-diaries-ctse',
    authDomain: 'cheezy-diaries-ctse.firebaseapp.com',
    storageBucket: 'cheezy-diaries-ctse.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbirS1XWoQAaAnM_RRBRfrx1wnRxlGeT4',
    appId: '1:735015269216:android:c01e17b307a2c07ea6a405',
    messagingSenderId: '735015269216',
    projectId: 'cheezy-diaries-ctse',
    storageBucket: 'cheezy-diaries-ctse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8157Bm1QuR3gBmRpcxvgLbg_U-CAuGFQ',
    appId: '1:735015269216:ios:7e9ce4ad9f7ccd75a6a405',
    messagingSenderId: '735015269216',
    projectId: 'cheezy-diaries-ctse',
    storageBucket: 'cheezy-diaries-ctse.appspot.com',
    iosClientId: '735015269216-ggq81ikqgqn8ngbokbfp2k6kv81ef3vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cheezyDiaryRecipieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8157Bm1QuR3gBmRpcxvgLbg_U-CAuGFQ',
    appId: '1:735015269216:ios:7e9ce4ad9f7ccd75a6a405',
    messagingSenderId: '735015269216',
    projectId: 'cheezy-diaries-ctse',
    storageBucket: 'cheezy-diaries-ctse.appspot.com',
    iosClientId: '735015269216-ggq81ikqgqn8ngbokbfp2k6kv81ef3vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cheezyDiaryRecipieApp',
  );
}
